[project]
name = "marl-adversarial-market"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pettingzoo>=1.25.0",
    "torch>=2.9.1",
]
